// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YGODuelSimulator.Data;

#nullable disable

namespace YGODuelSimulator.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706141816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("YGODuelSimulator.Models.Card", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archetype")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribute")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanGoat")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanOcg")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanTcg")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Def")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasEffect")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("KonamiId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OcgDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TcgDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YgoprodeckUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Archetype");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardFormats");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ApiImageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrlCropped")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrlSmall")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardImages");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardLinkMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardLinkMarkers");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmazonPrice")
                        .HasColumnType("TEXT");

                    b.Property<long>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardmarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoolstuffincPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("EbayPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("TcgplayerPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardPrices");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetRarity")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetRarityCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardFormat", b =>
                {
                    b.HasOne("YGODuelSimulator.Models.Card", "Card")
                        .WithMany("Formats")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardImage", b =>
                {
                    b.HasOne("YGODuelSimulator.Models.Card", "Card")
                        .WithMany("Images")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardLinkMarker", b =>
                {
                    b.HasOne("YGODuelSimulator.Models.Card", "Card")
                        .WithMany("LinkMarkers")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardPrice", b =>
                {
                    b.HasOne("YGODuelSimulator.Models.Card", "Card")
                        .WithMany("Prices")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.CardSet", b =>
                {
                    b.HasOne("YGODuelSimulator.Models.Card", "Card")
                        .WithMany("Sets")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("YGODuelSimulator.Models.Card", b =>
                {
                    b.Navigation("Formats");

                    b.Navigation("Images");

                    b.Navigation("LinkMarkers");

                    b.Navigation("Prices");

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
